version: '3.7'
services:

  ## Domain
  frontend:
    build: ../application/frontend

  imageorchestrator:
    build:
      context: ../application
      args:
        SERVICE: imageorchestrator

  imageholder:
    build:
      context: ../application
      args:
        SERVICE: imageholder

  imagerotator:
    build:
      context: ../application
      args:
        SERVICE: imagerotator

  imagegrayscale:
    build:
      context: ../application
      args:
        SERVICE: imagegrayscale

  imageresize:
    build:
      context: ../application
      args:
        SERVICE: imageresize

  imageflip:
    build:
      context: ../application
      args:
        SERVICE: imageflip

  imagethumbnail:
    build:
      context: ../application
      args:
        SERVICE: imagethumbnail

  traffic-gen:
    build: ../application/traffic-gen

  mongodb-service:
    image: mongo:3.2.12
    # See https://github.com/docker-library/docs/tree/master/mongo#setting-wiredtiger-cache-size-limits
    command: "--wiredTigerCacheSizeGB 2"
    ports:
      - '27017'
    volumes:
      - olly-mongodb:/data/db

volumes:
  olly-mongodb:
    driver: local
